name: provider_value
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  dio: ^5.9.2
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  json_annotation: ^4.11.0
  json_serializable: ^6.13.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.12.2
  freezed: ^3.2.5

flutter:
  uses-material-design: true
